# Generated by Django 5.0.1 on 2024-02-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_query_resolution_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='resolution_status',
            field=models.CharField(choices=[('RESOLVED', 'Resolved'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('DECLINED', 'Declined')], max_length=20),
        ),
    ]
