# Generated by Django 5.0.1 on 2024-02-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_query_resolution_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='resolution_status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('DECLINED', 'Declined'), ('RESOLVED', 'Resolved')], max_length=20),
        ),
    ]
