# Generated by Django 5.0.1 on 2024-02-22 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_query_resolution_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='classschedule',
            name='facilator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='meeting_type',
            field=models.CharField(choices=[('CLASS SESSION', 'Class Sessions'), ('WELLNESS SESSION', 'Wellness Sessions'), ('GUEST_LECTURE', 'Guest Lecture')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='repeat_frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MNTHLY', 'Monthly')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='resolution_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('DECLINED', 'Declined'), ('IN_PROGRESS', 'In Progress')], max_length=20),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='main.course'),
        ),
    ]
