# Generated by Django 5.0.1 on 2024-02-28 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_facilator_classschedule_facilitator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='facilitator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilitator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='query',
            name='resolution_status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('PENDING', 'Pending'), ('DECLINED', 'Declined')], max_length=20),
        ),
    ]
