# Generated by Django 5.0.1 on 2024-03-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_imuser_is_blocked_imuser_permanent_login_fail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imuser',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='imuser',
            name='unique_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='imuser',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='imuser',
            name='user_type',
            field=models.CharField(choices=[('EIT', 'EIT'), ('TEACHING_FELLOW', 'TEACHING_FELLOW'), ('ADMIN_STAFF', 'ADMIN_STAFF'), ('ADMIN', 'ADMIN')], default='EIT', max_length=20),
        ),
    ]
