# Generated by Django 5.0.1 on 2024-03-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_query_resolution_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='query_type',
            field=models.CharField(choices=[('DECLINED', 'Declined'), ('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('IN_PROGRESS', 'In Progress')], default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='query',
            name='resolution_status',
            field=models.CharField(blank=True, choices=[('KITCHEN', 'Kitchen'), ('LOGITISTICS', 'Logistics'), ('FACILITIES', 'Facilities')], max_length=20, null=True),
        ),
    ]
