# Generated by Django 5.0.1 on 2024-02-22 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_cohort_end_date_alter_cohort_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
