# Generated by Django 5.0.1 on 2024-02-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_course_date_created_alter_course_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
