# Generated by Django 5.0.1 on 2024-02-10 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_cohort_imuser_cohortmember_cohort_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cohortmember',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cohort_member', to='users.imuser'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_author', to='users.imuser'),
        ),
        migrations.AlterField(
            model_name='cohortmember',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_member_author', to='users.imuser'),
        ),
    ]
